### ISSUE TITLE
Package install hangs during chocolatey's automated testing

### ISSUE THREAD

**Issue by dusek** [bramd/chocolatey-nvda#3]
See https://gist.github.com/choco-bot/b3a49a1de9a3aedf03f1, https://chocolatey.org/packages/nvda/2015.4 - maintainer comment from 29 Feb 2016

For what it's worth, I too can confirm that running `choco install nvda -version 2016.1` successfully installs the package on Windows 7 SP1 32-bit Czech, without any hang (command exits in a few seconds).

**Comment by dusek** [comment]
As the package is now being successfully regularly updated and approved on chocolatey.org, I think this can be closed.

**Comment by bramd** [comment]
That's correct, I forgot to close this one. Thanks!
